name: Release

on: 
 push:
   tags:
     - v*.*.*

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build container 
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ludea/chatserver:${{ github.ref_name }}
          ludea/chatserver:latest
        target: final
        platforms: linux/amd64, linux/arm64         
  
